/* Boards to Bedside service worker — GENERATED by build_ship.py, do not edit by hand. */
const CACHE='btb-v114';
const CORE=['./index.html','./manifest.json','./favicon.ico',
            './assets/icon-192.png','./assets/icon-512.png','./assets/apple-touch-icon-180.png'];

self.addEventListener('install',e=>{
  /* add() one at a time: addAll() is atomic, so a single missing icon would abort the
     entire install and leave the app with no worker at all. */
  e.waitUntil(caches.open(CACHE)
    .then(c=>Promise.all(CORE.map(u=>c.add(u).catch(()=>{}))))
    .then(()=>self.skipWaiting()));
});

self.addEventListener('activate',e=>{
  e.waitUntil(caches.keys()
    .then(keys=>Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k))))
    .then(()=>self.clients.claim()));
});

self.addEventListener('fetch',e=>{
  const req=e.request;
  if(req.method!=='GET') return;
  let url;
  try{ url=new URL(req.url); }catch(err){ return; }
  if(url.origin!==self.location.origin) return;

  if(req.mode==='navigate'||req.destination==='document'){
    e.respondWith(
      fetch(req).then(res=>{
        if(res&&res.status===200){
          const copy=res.clone();
          caches.open(CACHE).then(c=>c.put('./index.html',copy)).catch(()=>{});
        }
        return res;
      }).catch(()=>caches.match('./index.html').then(r=>r||caches.match(req)))
    );
    return;
  }

  e.respondWith(
    caches.match(req).then(hit=>hit||fetch(req).then(res=>{
      if(res&&res.status===200&&res.type==='basic'){
        const copy=res.clone();
        caches.open(CACHE).then(c=>c.put(req,copy)).catch(()=>{});
      }
      return res;
    }))
  );
});
